# Generated by Django 4.2.18 on 2025-02-02 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarked_hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
